# Generated by Django 2.2.4 on 2019-09-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190901_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_time_end',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_time_start',
            new_name='time_start',
        ),
    ]
