# Generated by Django 2.2.4 on 2019-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190901_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['creator'], name='events_even_creator_f6258f_idx'),
        ),
    ]
