# Generated by Django 2.2.4 on 2019-09-05 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190905_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(blank=True, related_name='event_attendations', to=settings.AUTH_USER_MODEL),
        ),
    ]
